// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvH0nR1d66TeA5XQqmmncbJIToKSrlaC4',
    appId: '1:1005241337196:web:04b61ed5a22c6c80e9df49',
    messagingSenderId: '1005241337196',
    projectId: 'quickbite-28d6b',
    authDomain: 'quickbite-28d6b.firebaseapp.com',
    storageBucket: 'quickbite-28d6b.firebasestorage.app',
    measurementId: 'G-1936PQ9KCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJLbJOXDIua_izhPxf38vKUb6QsHjjwxQ',
    appId: '1:1005241337196:android:aca826d64b1904d3e9df49',
    messagingSenderId: '1005241337196',
    projectId: 'quickbite-28d6b',
    storageBucket: 'quickbite-28d6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWgh2C43_JvKjvFZOox3q1oC08dSXhi9E',
    appId: '1:1005241337196:ios:7f0728c855ef86b7e9df49',
    messagingSenderId: '1005241337196',
    projectId: 'quickbite-28d6b',
    storageBucket: 'quickbite-28d6b.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWgh2C43_JvKjvFZOox3q1oC08dSXhi9E',
    appId: '1:1005241337196:ios:7f0728c855ef86b7e9df49',
    messagingSenderId: '1005241337196',
    projectId: 'quickbite-28d6b',
    storageBucket: 'quickbite-28d6b.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvH0nR1d66TeA5XQqmmncbJIToKSrlaC4',
    appId: '1:1005241337196:web:c66d74b1903f3df6e9df49',
    messagingSenderId: '1005241337196',
    projectId: 'quickbite-28d6b',
    authDomain: 'quickbite-28d6b.firebaseapp.com',
    storageBucket: 'quickbite-28d6b.firebasestorage.app',
    measurementId: 'G-YPZL8EBDDT',
  );
}
